name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Java 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin' 

    - name: Install Clojure CLI
      run: |
        sudo apt update
        sudo apt install -y curl gnupg
        curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
        chmod +x linux-install.sh
        sudo ./linux-install.sh

    - uses: actions/checkout@v4

    - name: Install dependencies
      run: clojure -P

    - name: Run tests
      run: clojure -M:test
